
disabled_rules:
- trailing_whitespace
- force_cast
- function_body_length
- closure_parameter_position


included:

excluded:
- Pods


identifier_name:
  min_length:
    warning: 1

trailing_whitespace:
